[technote]
id = "SITCOMTN-152"
series_id = "SITCOMTN"
canonical_url = "https://sitcomtn-152.lsst.io"
github_url = "https://github.com/lsst-sitcom/sitcomtn-152"
github_default_branch = "main"
date_created = 2025-01-07T22:38:07Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Elana K."
name.family = "Urbach"
internal_id = "urbachek"
orcid = "https://orcid.org/0000-0002-3205-2484"
[[technote.authors.affiliations]]
name = "Department of Physics"
internal_id = "Harvard-Physics"
address = "Harvard University, 17 Oxford St., Cambridge MA 02138, USA"
